services:
  - type: web
    name: gibbon-school
    env: docker
    plan: free
    branch: v30.0.00
    dockerfilePath: Dockerfile         # Gibbon app Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql-service
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: gibbon
      - key: DB_USER
        value: gibbon
      - key: DB_PASS
        value: gibbonpass

  - type: worker
    name: mysql-service
    env: docker
    plan: free
    branch: v30.0.00
    dockerfilePath: Dockerfile.mysql   # MySQL Dockerfile
    buildFilter:
      paths:
        - init.sql
    autoDeploy: false
    startCommand: ""
