services:
  - type: web
    name: gibbon-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql-service
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: gibbon
      - key: DB_USER
        value: gibbon
      - key: DB_PASS
        value: gibbonpass

  - type: private
    name: mysql-service
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - init.sql
    buildCommand: ""
    startCommand: ""
